/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ProjectBlocks
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PROJECTBLOCKS_API_H
#define INCLUDED_PROJECTBLOCKS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ProjectBlocks_EXPORTS
#define PROJECTBLOCKS_API __GR_ATTR_EXPORT
#else
#define PROJECTBLOCKS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PROJECTBLOCKS_API_H */
